--liquibase formatted sql

--changeset initial:1

-- Meanings table: core semantic units
CREATE TABLE meanings
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content       CLOB        NOT NULL,
    sources       CLOB        NOT NULL DEFAULT '[]', -- JSON as text
    metadata      CLOB        NOT NULL DEFAULT '{}', -- JSON as text
    embedding     CLOB,                              -- simulate vector as JSON or base64
    model_version VARCHAR(32) NOT NULL,
    created_at    TIMESTAMP            DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP            DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE memories
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind             VARCHAR(32)      NOT NULL,
    content          CLOB             NOT NULL,
    related_meanings CLOB             NOT NULL DEFAULT '[]',
    weight           DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    last_accessed    TIMESTAMP                 DEFAULT CURRENT_TIMESTAMP,
    times_seen       INT              NOT NULL DEFAULT 0,
    model_version    VARCHAR(32)      NOT NULL,
    created_at       TIMESTAMP                 DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP                 DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dialogs
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id    VARCHAR(255) NOT NULL,
    started_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ended_at      TIMESTAMP,
    model_version VARCHAR(32)  NOT NULL,
    summary       CLOB      DEFAULT '{}',
    metadata      CLOB      DEFAULT '{}'
);

CREATE TABLE messages
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dialog_id    BIGINT      NOT NULL,
    role         VARCHAR(32) NOT NULL,
    content_text CLOB        NOT NULL,
    summary      CLOB,
    lang         VARCHAR(16),
    content_json CLOB,                   -- опционально: для структурных ответов
    metadata     CLOB,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (dialog_id) REFERENCES dialogs (id) ON DELETE CASCADE
);

CREATE INDEX idx_messages_dialog_id ON messages (dialog_id);

CREATE TABLE model_actions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type   VARCHAR(255) NOT NULL,
    payload       CLOB         NOT NULL,
    applied_by    VARCHAR(32)  NOT NULL,
    model_version VARCHAR(32)  NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
